#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export TERM=xterm-256color

if [[ "$OSTYPE" == "darwin"* ]]; then
	eval "$(rbenv init -)"
fi
# elif [[ "$OSTYPE" == "linux-gnu" ]]; then
# fi

alias lsa="ls -alG"

alias subf="subl --command toggle_full_screen" # (sub)lime (f)ullscreen
alias vim="nvim"
alias nots="jupyter notebook --script"
alias notc="jupyter nbconvert"

alias workon="source bin/activate"
alias workoff="deactivate"

# http://gggritso.com/human-git-aliases
alias branches="branch -a"
alias tags="tag"
alias stashes="stash list"

alias unstage="reset -q HEAD --"
alias discard="checkout --"
alias uncommit="reset --mixed HEAD~"
alias amend="commit --amend"

alias nevermind="!git reset --hard HEAD && git clean -d -f"

alias graph="graph = log --graph -10 --branches --remotes --tags  --format=format:'%Cgreen%h %Creset• %<(75,trunc)%s (%cN, %cr) %Cred%d' --date-order"

alias precommit="diff --cached --diff-algorithm=minimal -w"

# http://stackoverflow.com/questions/3375697/useful-gcc-flags-for-c
alias ccnf=" 
clang \
-Wall \
-Wextra \
-Wpedantic \
-Wshadow \
-Wstrict-prototypes \
-Wmisleading-indentation \
" # (c)ompile (C) (n)ormal (f)lags

alias ccsf="
ccwf \
-Wundef \
-Wfloat-equal \
-Wpointer-arith \
-Wcast-align \
-Wwrite-strings \
-Waggregate-return \
" # (c)ompile (C) (s)trict (f)lags
