#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export TERM=xterm-256color

if [[ "$OSTYPE" == "darwin"* ]]; then
	eval "$(rbenv init -)"
fi
# elif [[ "$OSTYPE" == "linux-gnu" ]]; then
# fi

alias subf="subl --command toggle_full_screen"
alias workon="source bin/activate"
alias vim="nvim"
